### ISSUE TITLE
is this the best place to go for the latest snap-guest?

### ISSUE THREAD

**Issue by mccun934** [lzap/snap-guest#5]
We have:

https://github.com/Katello/snap-guest

and:

https://github.com/lzap/snap-guest

yours seems way more up to date and Katello's is forked from you. what is the purpose of the one that is part of the Katello org?

**Comment by lzap** [comment]
I have no clue Mike, I did not create it.

**Comment by lzap** [comment]
Ok I have deleted Katello fork, not sure who forked it, but it was obviously confusing some Katello friendly users. But if you are willing to cooperate on this effort, I am happy to move it there and make it default site.
