### ISSUE TITLE
Doesn't work in Fedora 18

### ISSUE THREAD

**Issue by rarguello** [lzap/snap-guest#8]
There is a bug in Fedora 18, in the package libguestfs-1.20.1-2, that makes snap-guest stop working.

FIX: You need to upgrade to libguestfs-1.20.1-3.

It's in the Fedora 18 updates-testing repo, or in Koji:
https://admin.fedoraproject.org/updates/libguestfs-1.20.1-3.fc18

Please add karma so it's pushed to the stable repo.

**Comment by iNecas** [comment]
Thanks for reporting, carma added :)

**Comment by lzap** [comment]
Thanks!

```
This update has reached the stable karma threshold and will be pushed to the stable updates repository
```

**Comment by iNecas** [comment]
The same issue was in F17, karma here https://admin.fedoraproject.org/updates/FEDORA-2013-1213/libguestfs-1.18.11-2.fc17
